added PHP_PATH variable and formatted pre-push script

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,70 +1,51 @@
-#!/bin/sh
+#!/bin/bash
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local oid> <remote ref> <remote oid>
-#
+function clean_exit() {
+	pkill webserv > /dev/null 2>&1
+	make fclean
+	if [ $1 -eq 1 ]
+	then
+		echo "FAILED"
+	 else
+		echo "OK"
+	fi
+	exit $1
+}
 
-trap "pkill webserv > /dev/null 2>&1; make fclean ; exit 1" SIGHUP SIGINT SIGTERM
+function assert() {
+	if !($1)
+	then
+		[[ -n "$2" ]] && echo $2
+		clean_exit 1
+	fi
+}
+
+trap "clean_exit 1" SIGHUP SIGINT SIGTERM
 remote="$1"
 url="$2"
 
+assert "which python3" "please install python3"
+assert "which php-cgi" "please install php-cgi"
+
 make re config
 ./webserv ./conf/webserv.conf > /dev/null 2>&1 &
-sleep 1
-if !(pgrep webserv > /dev/null)
-	then
-		echo "FAILED"
-		exit 1
-fi
-if !(python3 ./tests/test.py);
-then
-	pkill webserv > /dev/null 2>&1
-	echo "FAILED"
-	exit 1
-fi
 
-pkill webserv > /dev/null 2>&1 
-
-./webserv ./conf/webserv_cmp.conf > /dev/null 2>&1 &
 sleep 1
-if !(pgrep webserv > /dev/null)
-	then
-		echo "FAILED"
-		exit 1
-fi
-if !(python3 tests/compare_test/compare_test.py webserv)
-then
-	pkill webserv > /dev/null 2>&1
-	echo "FAILED"
-	exit 1
-fi
+
+assert "pgrep webserv"
+assert "python3 ./tests/test.py"
+
 pkill webserv > /dev/null 2>&1
+./webserv ./conf/webserv_cmp.conf > /dev/null 2>&1 &
 
-
-./webserv ./conf/multi_name.conf > /dev/null 2>&1 &
 sleep 1
-if !(tests/multi_name.sh)
-then
-	pkill webserv > /dev/null 2>&1
-	echo "FAILED"
-	exit 1
-fi
-# ./webserv ./conf/tester.conf
+assert "pgrep webserv"
+assert "python3 tests/compare_test/compare_test.py webserv"
 
-make fclean
+pkill webserv > /dev/null 2>&1
+./webserv ./conf/multi_name.conf > /dev/null 2>&1 &
 
-echo "OK"
-exit 0
+sleep 1
+assert "tests/multi_name.sh"
+
+clean_exit 0
